
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 14 17:27:40 CST 2022
//----------------------------------------------------

package Clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VerbosIrregPresent = 26;
  public static final int CS_Condicionales = 42;
  public static final int AdIndefinidos = 8;
  public static final int CS_Finales = 46;
  public static final int AdDemostrativos = 4;
  public static final int PronPerSingulares = 11;
  public static final int AdCalificativos = 5;
  public static final int PronDemostrativos = 14;
  public static final int Cs_Comparativas = 48;
  public static final int VerbIs = 19;
  public static final int CS_Concetivas = 47;
  public static final int AdvDuda = 35;
  public static final int VerbosRegPresent = 23;
  public static final int ArtDefinidos = 9;
  public static final int AdvAfirmacion = 33;
  public static final int AuxGoing = 49;
  public static final int PronInterrogativos = 15;
  public static final int CC_Copulativas = 38;
  public static final int VerbosRegIng = 24;
  public static final int SigPunt = 52;
  public static final int PronI = 54;
  public static final int PronPer = 13;
  public static final int VerbWas = 17;
  public static final int AdvModo = 32;
  public static final int CC_Distributivas = 40;
  public static final int CS_Concesivas = 45;
  public static final int PronPerPlurales = 12;
  public static final int ArtIndefinidos = 10;
  public static final int EOF = 0;
  public static final int AdvNegacion = 34;
  public static final int AdNumOrdinal = 7;
  public static final int error = 1;
  public static final int AdvTiempo = 29;
  public static final int VerbAre = 20;
  public static final int VerbBe = 21;
  public static final int ERROR = 53;
  public static final int CC_Explicativas = 37;
  public static final int AdvLugar = 30;
  public static final int VerbBeing = 22;
  public static final int AdNumCardinal = 6;
  public static final int VerbRegPast = 25;
  public static final int AdvCantidad = 31;
  public static final int VerbWere = 18;
  public static final int CC_Adversativas = 39;
  public static final int VerbAm = 16;
  public static final int preposiciones = 36;
  public static final int CC_Disyuntivas = 41;
  public static final int AuxWill = 50;
  public static final int Sustantivos = 2;
  public static final int AdPosesivos = 3;
  public static final int CS_Consecutivas = 44;
  public static final int VerbIrregIng = 27;
  public static final int CS_Casuales = 43;
  public static final int VerbIrregPast = 28;
  public static final int AuxDo = 51;
}

